# Generated by Django 4.2.13 on 2024-05-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='images/default_profile.png', upload_to='images/'),
        ),
    ]
